"""
Auto-generates docs/index.html from whatever PDFs exist under docs/materials/.

Layout convention:
  docs/materials/<unit-folder>/<file>.pdf   -> grouped under an "<unit-folder>" heading
  docs/materials/<file>.pdf                 -> grouped under a "General" heading

Run manually with:  python scripts/build_index.py
(Normally this runs automatically via .github/workflows/build-index.yml)
"""

import html
import pathlib

MATERIALS_DIR = pathlib.Path("docs/materials")
OUTPUT_FILE = pathlib.Path("docs/index.html")


def title_from_name(name):
    """Turn 'unit-3_worksheet.pdf' or 'unit-3' into 'Unit 3 Worksheet' / 'Unit 3'."""
    stem = pathlib.Path(name).stem
    stem = stem.replace("-", " ").replace("_", " ")
    return " ".join(word.capitalize() for word in stem.split())


def list_items(pdfs, base_dir):
    lines = []
    for pdf in pdfs:
        rel = pdf.relative_to(base_dir)  # path relative to docs/
        label = title_from_name(pdf.name)
        lines.append(f'    <li><a href="{html.escape(str(rel))}">{html.escape(label)}</a></li>')
    return "\n".join(lines)


def build_sections():
    sections = []
    if not MATERIALS_DIR.exists():
        return sections

    docs_dir = MATERIALS_DIR.parent

    # Grouped by subfolder (unit), sorted alphabetically
    for folder in sorted(p for p in MATERIALS_DIR.iterdir() if p.is_dir()):
        pdfs = sorted(folder.glob("*.pdf"))
        if not pdfs:
            continue
        heading = title_from_name(folder.name)
        items = list_items(pdfs, docs_dir)
        sections.append(f"  <h2>{html.escape(heading)}</h2>\n  <ul>\n{items}\n  </ul>")

    # Loose PDFs directly in docs/materials/ (no subfolder)
    loose = sorted(MATERIALS_DIR.glob("*.pdf"))
    if loose:
        items = list_items(loose, docs_dir)
        sections.append(f"  <h2>General</h2>\n  <ul>\n{items}\n  </ul>")

    return sections


def build_html():
    sections = build_sections()
    body = "\n\n".join(sections) if sections else "  <p><em>Materials coming soon.</em></p>"

    return f"""<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<title>Kool Kat Science — Materials</title>
<style>
  body {{ font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", Helvetica, Arial, sans-serif; max-width: 720px; margin: 3rem auto; padding: 0 1.5rem; color: #1a1a1a; line-height: 1.5; }}
  h1 {{ font-size: 1.5rem; margin-bottom: 0.25rem; }}
  p.subtitle {{ color: #555; margin-top: 0; }}
  h2 {{ font-size: 1.1rem; margin-top: 2rem; border-bottom: 1px solid #ddd; padding-bottom: 0.25rem; }}
  ul {{ padding-left: 1.25rem; }}
  li {{ margin: 0.35rem 0; }}
  a {{ color: #0b6b3a; text-decoration: none; }}
  a:hover {{ text-decoration: underline; }}
  footer {{ margin-top: 3rem; font-size: 0.85rem; color: #888; }}
</style>
</head>
<body>
  <h1>Kool Kat Science — Materials</h1>
  <p class="subtitle">Worksheets, handouts, and unit files for students.</p>

{body}

  <footer>Kool Kat Science — this page is auto-generated by scripts/build_index.py. Don't hand-edit; it will be overwritten on the next PDF upload.</footer>
</body>
</html>
"""


def main():
    OUTPUT_FILE.write_text(build_html(), encoding="utf-8")
    print(f"Wrote {OUTPUT_FILE}")


if __name__ == "__main__":
    main()
